#!/bin/bash
set -e

# parse arguments
POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    --docker-image)
    DOCKER_IMAGE="$2"
    shift # past argument
    shift # past value
    ;;
    --base-model-name)
    BASE_MODEL_NAME="$2"
    shift # past argument
    shift # past value
    ;;
    *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
esac
done


# run predictions
DOCKER_RUN="docker run
  --entrypoint entrypoints/entrypoint.predict.cpu.sh \
  -v "$(pwd)"/models/MobileNet/weights_mobilenet_technical_0.11.hdf5:/src/weights_technical.hdf5
  -v "$(pwd)"/models/MobileNet/weights_mobilenet_aesthetic_0.07.hdf5:/src/weights_aesthetic.hdf5
  -v "$(pwd)"/src/output:/src/output
  $DOCKER_IMAGE $BASE_MODEL_NAME /src/$BASENAME_IS"

eval $DOCKER_RUN
